### PR TITLE
Fix #8 - workaround for dmd issue 19407

### LINKED ISSUE #8: No longer works with recursive types with separate compilation
The code below fails to compile:

```d
// app.d
import type;
```

```d
// type.d
import sumtype;

alias Type = SumType!(Bool, Pointer);

struct Bool {}

struct Pointer {
    Type* pointeeType;
}
```

```
% dmd -c -I~/.dub/packages/sumtype-0.6.4/sumtype/src app.d
/usr/include/dlang/dmd/std/traits.d(2678): Error: unable to determine fields of Pointer because of forward references
/usr/include/dlang/dmd/std/traits.d(3760): Error: template instance `std.traits.FieldTypeTuple!(Pointer)` error instantiating
/usr/include/dlang/dmd/std/meta.d(887):        instantiated from here: F!(Pointer)
/usr/include/dlang/dmd/std/meta.d(893):        instantiated from here: anySatisfy!(hasElaborateDestructor, Pointer)
/home/atila/.dub/packages/sumtype-0.6.4/sumtype/src/sumtype.d(303):        instantiated from here: anySatisfy!(hasElaborateDestructor, Bool, Pointer)
type.d(4):        instantiated from here: SumType!(Bool, Pointer)
```

It works fine if the two files are compiled together.

This regression was introduced in this commit:

```
commit ed05b67ee6f338aaad50175e258c88f51b5cb641
Author: Paul Backus <snarwin@gmail.com>
Date:   Sun Aug 5 17:35:12 2018 -0400

    Handle types with destructors correctly
    
    std.algorithm.mutation.moveEmplace is used in opAssign as a workaround
    for dlang issue 19150.
```

### PR DESCRIPTION
**Pull request by atilaneves**
The PR just adds a compile-time check to work around the issue.

### CODE REVIEW

**Comment by pbackus** [comment]
This change can cause the same program to behave differently depending on whether it's compiled separately or all together.

Here's the test case I used:

```d
// app.d
import type;

void main()
{
    Type t = Pointer(null);
}

// type.d
import sumtype;

alias Type = SumType!(Bool, Pointer);

struct Bool {}

struct Pointer {
    Type* pointeeType;

    ~this()
    {
        import std.stdio: writeln;
        writeln("destructor");
    }
}
```

```make
# Makefile
all: separate together

together: app.d type.d sumtype.d
	dmd -of=$@ $^

separate: app.o type.o sumtype.o
	# Copied from `dmd -v` output
	cc $^ -o separate -m64 -Xlinker --export-dynamic \
	-L/usr/lib/x86_64-linux-gnu -Xlinker -Bstatic -lphobos2 \
	-Xlinker -Bdynamic -lpthread -lm -lrt -ldl

%.o: %.d
	dmd -c -I. $<

app.d: sumtype.d type.d

type.d: sumtype.d

sumtype.d:
	# This is the version from the PR
	wget https://raw.githubusercontent.com/pbackus/sumtype/680e98da4d9041bbd5fd5b1f2aab19fb09996522/src/sumtype.d

clean:
	rm -f *.o separate together
```

Comparing the output gives the following result:

```
$ diff -u <(./separate) <(./together)
--- /dev/fd/63  2018-11-16 17:11:03.497105469 -0500
+++ /dev/fd/62  2018-11-16 17:11:03.497105469 -0500
@@ -1,2 +1,3 @@
 destructor
 destructor
+destructor
```

In other words,  there's a destructor call that's omitted in the separately-compiled version.

**Comment by atilaneves** [comment]
Ugh, good point.

This is a blocker for me right now so I'm trying to figure out what the least bad option is. A `version` block?

**Comment by pbackus** [comment]
Would generating the destructor unconditionally when the `anySatisfy` test fails to compile work?

There are individual `hasElaborateDestructor` tests inside the destructor itself. The purpose of the `anySatisfy` test is just to avoid generating a no-op destructor.

**Comment by pbackus** [comment]
@atilaneves Let me know if this solves your issue:

https://github.com/pbackus/sumtype/compare/fix-separate-compilation

**Comment by atilaneves** [comment]
@pbackus Yes, that solves the issue. Thanks!
